"""immutable outreach drafts

Revision ID: 0d1db464e1c2
Revises: 20260920_09
Create Date: 2026-09-20 12:47:58.531524

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0d1db464e1c2"
down_revision: str | Sequence[str] | None = "20260920_09"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record_outreach_contexts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("artifact_version", sa.Integer(), nullable=False),
        sa.Column("artifact_hash", sa.String(length=64), nullable=False),
        sa.Column("lineage_hash", sa.String(length=64), nullable=False),
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("recipient_source_id", sa.UUID(), nullable=False),
        sa.Column("contact_source_id", sa.UUID(), nullable=False),
        sa.Column("contact_verification_id", sa.UUID(), nullable=False),
        sa.Column("contact_resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("contact_valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.Column("offer_acceptance_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("prompt_artifact_id", sa.UUID(), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("prompt_hash", sa.String(length=64), nullable=False),
        sa.Column("model_config_id", sa.UUID(), nullable=False),
        sa.Column("model_config_workflow_id", sa.UUID(), nullable=False),
        sa.Column("model_config_version", sa.UUID(), nullable=False),
        sa.Column("recipient_mode", sa.String(length=32), nullable=False),
        sa.Column("recipient_label", sa.String(length=200), nullable=True),
        sa.Column("recipient_label_evidence_id", sa.UUID(), nullable=True),
        sa.Column("greeting", sa.String(length=200), nullable=False),
        sa.Column("frozen_by", sa.UUID(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "recipient_mode IN ('NAMED_PERSON','ROLE_INBOX','GENERAL_BUSINESS_INBOX')"
        ),
        sa.CheckConstraint(
            "artifact_version>0 AND prompt_version>0 AND contact_resolved_at<contact_valid_until AND lineage_hash ~ '^[0-9a-f]{64}$'"
        ),
        sa.CheckConstraint(
            "(recipient_mode='GENERAL_BUSINESS_INBOX' AND recipient_label IS NULL AND recipient_label_evidence_id IS NULL AND greeting='Hello team') OR "
            "(recipient_mode='NAMED_PERSON' AND recipient_label IS NOT NULL AND recipient_label_evidence_id IS NOT NULL AND greeting='Hi '||recipient_label) OR "
            "(recipient_mode='ROLE_INBOX' AND recipient_label IS NOT NULL AND recipient_label_evidence_id IS NOT NULL AND greeting='Hello '||recipient_label||' team')"
        ),
        sa.ForeignKeyConstraint(["artifact_id"], ["record_artifacts.id"]),
        sa.ForeignKeyConstraint(
            ["cohort_id", "experiment_id"],
            [
                "record_qualification_cohorts.id",
                "record_qualification_cohorts.experiment_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id", "experiment_id"],
            [
                "record_qualification_decisions.id",
                "record_qualification_decisions.experiment_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["contact_source_id", "experiment_id"],
            ["supply_facts.id", "supply_facts.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["contact_verification_id", "experiment_id"],
            ["supply_facts.id", "supply_facts.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["model_config_id", "model_config_workflow_id", "model_config_version"],
            ["gov_configs.id", "gov_configs.workflow_id", "gov_configs.version"],
        ),
        sa.ForeignKeyConstraint(["prompt_artifact_id"], ["record_artifacts.id"]),
        sa.ForeignKeyConstraint(
            ["recipient_label_evidence_id", "dossier_id"],
            [
                "record_qualification_evidence.id",
                "record_qualification_evidence.dossier_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id"),
        sa.UniqueConstraint("decision_id"),
        sa.UniqueConstraint("id", "dossier_id"),
        sa.UniqueConstraint("id", "experiment_id"),
    )
    op.create_table(
        "record_outreach_angles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=2000), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint("rank>0"),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["record_outreach_contexts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("context_id", "rank"),
        sa.UniqueConstraint("id", "context_id"),
    )
    op.create_table(
        "record_outreach_coverage",
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.Column("disposition", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=True),
        sa.CheckConstraint("(disposition='USED')=(reason_code IS NULL)"),
        sa.CheckConstraint(
            "disposition IN ('USED','NOT_USED','REJECTED_SENSITIVE','REJECTED_INTRUSIVE','REJECTED_IRRELEVANT','REJECTED_UNSUPPORTED')"
        ),
        sa.ForeignKeyConstraint(
            ["context_id", "dossier_id"],
            ["record_outreach_contexts.id", "record_outreach_contexts.dossier_id"],
        ),
        sa.ForeignKeyConstraint(
            ["evidence_id", "dossier_id"],
            [
                "record_qualification_evidence.id",
                "record_qualification_evidence.dossier_id",
            ],
        ),
        sa.PrimaryKeyConstraint("context_id", "evidence_id"),
    )
    op.create_table(
        "record_outreach_documents",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "kind IN ('LEAD_OPPORTUNITY_NARRATIVE','CONVERSATION_STRATEGY','OUTREACH_SEQUENCE_PLAN','EMAIL_DRAFT')"
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id", "experiment_id", "kind", "version", "content_hash"],
            [
                "record_artifacts.id",
                "record_artifacts.experiment_id",
                "record_artifacts.kind",
                "record_artifacts.version",
                "record_artifacts.content_hash",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["context_id", "experiment_id"],
            ["record_outreach_contexts.id", "record_outreach_contexts.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
        sa.UniqueConstraint("artifact_id", "context_id"),
    )
    op.create_table(
        "record_outreach_angle_evidence",
        sa.Column("angle_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["angle_id", "context_id"],
            ["record_outreach_angles.id", "record_outreach_angles.context_id"],
        ),
        sa.ForeignKeyConstraint(
            ["context_id", "evidence_id"],
            [
                "record_outreach_coverage.context_id",
                "record_outreach_coverage.evidence_id",
            ],
        ),
        sa.PrimaryKeyConstraint("angle_id", "evidence_id"),
    )
    op.create_table(
        "record_outreach_claims",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("text", sa.String(length=4000), nullable=False),
        sa.CheckConstraint("kind IN ('FACTUAL','COMMERCIAL')"),
        sa.CheckConstraint("ordinal>0"),
        sa.ForeignKeyConstraint(
            ["artifact_id", "context_id"],
            [
                "record_outreach_documents.artifact_id",
                "record_outreach_documents.context_id",
            ],
        ),
        sa.PrimaryKeyConstraint("artifact_id", "ordinal"),
        sa.UniqueConstraint("artifact_id", "ordinal"),
        sa.UniqueConstraint("artifact_id", "ordinal", "context_id"),
    )
    op.create_table(
        "record_outreach_sequence_steps",
        sa.Column("sequence_artifact_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("delay_days", sa.Integer(), nullable=False),
        sa.Column("objective", sa.String(length=1000), nullable=False),
        sa.CheckConstraint("ordinal>0 AND delay_days>=0"),
        sa.ForeignKeyConstraint(
            ["sequence_artifact_id", "context_id"],
            [
                "record_outreach_documents.artifact_id",
                "record_outreach_documents.context_id",
            ],
        ),
        sa.PrimaryKeyConstraint("sequence_artifact_id", "ordinal"),
    )
    op.create_table(
        "record_outreach_subjects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("strategy_artifact_id", sa.UUID(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("text", sa.String(length=998), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.CheckConstraint("rank>0"),
        sa.ForeignKeyConstraint(
            ["context_id"],
            ["record_outreach_contexts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_artifact_id", "context_id"],
            [
                "record_outreach_documents.artifact_id",
                "record_outreach_documents.context_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("context_id", "rank"),
        sa.UniqueConstraint("id", "context_id"),
    )
    op.create_table(
        "record_outreach_claim_evidence",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id", "ordinal", "context_id"],
            [
                "record_outreach_claims.artifact_id",
                "record_outreach_claims.ordinal",
                "record_outreach_claims.context_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["context_id", "evidence_id"],
            [
                "record_outreach_coverage.context_id",
                "record_outreach_coverage.evidence_id",
            ],
        ),
        sa.PrimaryKeyConstraint("artifact_id", "ordinal", "evidence_id"),
    )
    op.create_table(
        "record_outreach_claim_offer_fields",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("field_path", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id", "ordinal", "context_id"],
            [
                "record_outreach_claims.artifact_id",
                "record_outreach_claims.ordinal",
                "record_outreach_claims.context_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["offer_id", "field_path"],
            [
                "record_offer_field_sources.offer_id",
                "record_offer_field_sources.field_path",
            ],
        ),
        sa.PrimaryKeyConstraint("artifact_id", "ordinal", "field_path"),
    )
    op.create_table(
        "record_outreach_drafts",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("narrative_artifact_id", sa.UUID(), nullable=False),
        sa.Column("strategy_artifact_id", sa.UUID(), nullable=False),
        sa.Column("sequence_artifact_id", sa.UUID(), nullable=False),
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("recipient_mode", sa.String(length=32), nullable=False),
        sa.Column("greeting", sa.String(length=200), nullable=False),
        sa.CheckConstraint(
            "recipient_mode IN ('NAMED_PERSON','ROLE_INBOX','GENERAL_BUSINESS_INBOX')"
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id", "context_id"],
            [
                "record_outreach_documents.artifact_id",
                "record_outreach_documents.context_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["narrative_artifact_id", "context_id"],
            [
                "record_outreach_documents.artifact_id",
                "record_outreach_documents.context_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["sequence_artifact_id", "context_id"],
            [
                "record_outreach_documents.artifact_id",
                "record_outreach_documents.context_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["strategy_artifact_id", "context_id"],
            [
                "record_outreach_documents.artifact_id",
                "record_outreach_documents.context_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "context_id"],
            ["record_outreach_subjects.id", "record_outreach_subjects.context_id"],
        ),
        sa.PrimaryKeyConstraint("artifact_id"),
        sa.UniqueConstraint("artifact_id", "context_id"),
    )
    op.create_table(
        "record_outreach_subject_evidence",
        sa.Column("subject_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["context_id", "evidence_id"],
            [
                "record_outreach_coverage.context_id",
                "record_outreach_coverage.evidence_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["subject_id", "context_id"],
            ["record_outreach_subjects.id", "record_outreach_subjects.context_id"],
        ),
        sa.PrimaryKeyConstraint("subject_id", "evidence_id"),
    )
    op.create_table(
        "record_outreach_draft_angles",
        sa.Column("draft_artifact_id", sa.UUID(), nullable=False),
        sa.Column("context_id", sa.UUID(), nullable=False),
        sa.Column("angle_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.CheckConstraint("role IN ('PRIMARY','SUPPORTING')"),
        sa.ForeignKeyConstraint(
            ["angle_id", "context_id"],
            ["record_outreach_angles.id", "record_outreach_angles.context_id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_artifact_id", "context_id"],
            ["record_outreach_drafts.artifact_id", "record_outreach_drafts.context_id"],
        ),
        sa.PrimaryKeyConstraint("draft_artifact_id", "role"),
    )
    op.create_table(
        "record_outreach_draft_ctas",
        sa.Column("draft_artifact_id", sa.UUID(), nullable=False),
        sa.Column("text", sa.String(length=1000), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_artifact_id"],
            ["record_outreach_drafts.artifact_id"],
        ),
        sa.PrimaryKeyConstraint("draft_artifact_id"),
    )
    op.create_table(
        "record_outreach_validations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("draft_artifact_id", sa.UUID(), nullable=False),
        sa.Column("validator", sa.String(length=100), nullable=False),
        sa.Column("validator_version", sa.Integer(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("disposition", sa.String(length=8), nullable=False),
        sa.Column("reason_codes", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("validated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("disposition IN ('PASS','FAIL')"),
        sa.CheckConstraint("validator_version>0 AND cardinality(reason_codes)>=0"),
        sa.ForeignKeyConstraint(
            ["artifact_id", "experiment_id"],
            ["record_artifacts.id", "record_artifacts.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["draft_artifact_id"],
            ["record_outreach_drafts.artifact_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("artifact_id"),
        sa.UniqueConstraint("draft_artifact_id", "validator", "validator_version"),
    )
    op.add_column(
        "record_initial_outreach_policies",
        sa.Column("max_sequence_steps", sa.Integer(), nullable=True),
    )
    op.create_check_constraint(
        "record_initial_outreach_policies_sequence_check",
        "record_initial_outreach_policies",
        "max_sequence_steps IS NULL OR max_sequence_steps>0",
    )
    op.execute(
        "ALTER TABLE record_artifacts DROP CONSTRAINT record_artifacts_kind_check"
    )
    op.execute("""
ALTER TABLE record_artifacts ADD CONSTRAINT record_artifacts_kind_check CHECK(kind IN (
 'EXPERIMENT_BRIEF','IDEA_SEED','IDEA_CANDIDATE','IDEA_BRIEF','RESEARCH_PLAN','RESEARCH_EVIDENCE',
 'COMPETITOR_PROFILE','SERVICE_PROFILE','PRICE_OBSERVATION','MARKET_RESEARCH_REPORT',
 'MARKET_RESEARCH_RECOMMENDATION','RESEARCH_FEEDBACK_BRIEF','OFFER_RESEARCH_GAP_BRIEF',
 'DELIVERY_SCOPE_ESTIMATE','OFFER_DESIGN_INPUT_BUNDLE','COMMERCIAL_DESIGN_ENVELOPE',
 'OFFER_DESIGN_PROPOSAL','OFFER_PACKAGE','OFFER_QUALIFICATION_PROFILE','INITIAL_OUTREACH_POLICY',
 'OUTREACH_PROMPT_CONFIGURATION','OUTREACH_CONTEXT_BUNDLE','LEAD_OPPORTUNITY_NARRATIVE',
 'CONVERSATION_STRATEGY','OUTREACH_SEQUENCE_PLAN','EMAIL_DRAFT','DRAFT_VALIDATION_RESULT',
 'VALIDATION_RESULT','ACCEPTANCE_RECEIPT'))
""")
    op.execute(
        "ALTER FUNCTION record_payload_valid(text,jsonb) RENAME TO record_payload_valid_pre_outreach"
    )
    op.execute(r"""
CREATE FUNCTION record_payload_valid(kind text, value jsonb) RETURNS boolean
LANGUAGE sql IMMUTABLE AS $$
 SELECT CASE kind
  WHEN 'INITIAL_OUTREACH_POLICY' THEN
   record_json_exact(value,ARRAY['pricing','formal_proposal','detailed_scope','budget_question','primary_goal','max_sequence_steps'])
   AND value->>'pricing'='OMIT' AND value->>'formal_proposal'='FORBIDDEN'
   AND value->>'detailed_scope'='OMIT' AND value->>'budget_question'='FORBIDDEN'
   AND value->>'primary_goal'='START_RELEVANT_CONVERSATION'
   AND jsonb_typeof(value->'max_sequence_steps')='number' AND (value->>'max_sequence_steps')::integer>0
  WHEN 'OUTREACH_PROMPT_CONFIGURATION' THEN record_json_exact(value,ARRAY['template']) AND record_nonempty_text(value->'template')
  WHEN 'OUTREACH_CONTEXT_BUNDLE' THEN record_json_exact(value,ARRAY['status','recipient_mode','recipient_label','greeting']) AND value->>'status'='FROZEN' AND value->>'recipient_mode' IN ('NAMED_PERSON','ROLE_INBOX','GENERAL_BUSINESS_INBOX') AND record_nonempty_text(value->'greeting') AND ((value->>'recipient_mode'='GENERAL_BUSINESS_INBOX' AND value->'recipient_label'='null'::jsonb AND value->>'greeting'='Hello team') OR (value->>'recipient_mode'='NAMED_PERSON' AND record_nonempty_text(value->'recipient_label') AND value->>'greeting'='Hi '||(value->>'recipient_label')) OR (value->>'recipient_mode'='ROLE_INBOX' AND record_nonempty_text(value->'recipient_label') AND value->>'greeting'='Hello '||(value->>'recipient_label')||' team'))
  WHEN 'LEAD_OPPORTUNITY_NARRATIVE' THEN record_json_exact(value,ARRAY['text']) AND record_nonempty_text(value->'text')
  WHEN 'CONVERSATION_STRATEGY' THEN record_json_exact(value,ARRAY['text']) AND record_nonempty_text(value->'text')
  WHEN 'OUTREACH_SEQUENCE_PLAN' THEN record_json_exact(value,ARRAY['objective','step_count']) AND record_nonempty_text(value->'objective') AND jsonb_typeof(value->'step_count')='number' AND (value->>'step_count')::integer>0
  WHEN 'EMAIL_DRAFT' THEN record_json_exact(value,ARRAY['recipient_mode','greeting','subject','body']) AND value->>'recipient_mode' IN ('NAMED_PERSON','ROLE_INBOX','GENERAL_BUSINESS_INBOX') AND record_nonempty_text(value->'greeting') AND record_nonempty_text(value->'subject') AND record_nonempty_text(value->'body')
  WHEN 'DRAFT_VALIDATION_RESULT' THEN record_json_exact(value,ARRAY['validator','disposition','input_hash','reason_codes']) AND record_nonempty_text(value->'validator') AND value->>'disposition' IN ('PASS','FAIL') AND value->>'input_hash' ~ '^[0-9a-f]{64}$' AND jsonb_typeof(value->'reason_codes')='array'
  ELSE record_payload_valid_pre_outreach(kind,value) END
$$;

CREATE FUNCTION record_outreach_immutable() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'immutable outreach record'; END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION record_outreach_context_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE member record_qualification_cohort_members; decision record_qualification_decisions; matrix record_qualification_matrices; dossier record_qualification_dossiers; cohort record_qualification_cohorts; contact supply_contacts; recipient_source record_org_recipient_sources; cfg gov_configs; workflow gov_workflows;
BEGIN
 SELECT * INTO member FROM record_qualification_cohort_members WHERE cohort_id=NEW.cohort_id AND decision_id=NEW.decision_id;
 SELECT * INTO decision FROM record_qualification_decisions WHERE id=NEW.decision_id;
 SELECT * INTO matrix FROM record_qualification_matrices WHERE id=NEW.matrix_id;
 SELECT * INTO dossier FROM record_qualification_dossiers WHERE id=NEW.dossier_id;
 SELECT * INTO cohort FROM record_qualification_cohorts WHERE id=NEW.cohort_id;
 SELECT * INTO contact FROM supply_contacts WHERE candidate_id=NEW.candidate_id;
 SELECT * INTO recipient_source FROM record_org_recipient_sources WHERE id=NEW.recipient_source_id;
 SELECT * INTO cfg FROM gov_configs WHERE id=NEW.model_config_id;
 SELECT * INTO workflow FROM gov_workflows WHERE id=cfg.workflow_id;
 NEW.lineage_hash:=encode(sha256(convert_to(concat_ws(E'\n',
  NEW.experiment_id::text,NEW.artifact_id::text,NEW.artifact_version::text,NEW.artifact_hash,
  NEW.cohort_id::text,NEW.decision_id::text,NEW.matrix_id::text,NEW.dossier_id::text,
  NEW.candidate_id::text,NEW.organization_id::text,NEW.recipient_id::text,NEW.recipient_source_id::text,
  NEW.contact_source_id::text,NEW.contact_verification_id::text,NEW.contact_resolved_at::text,NEW.contact_valid_until::text,
  NEW.reservation_id::text,NEW.offer_acceptance_id::text,NEW.offer_id::text,NEW.profile_id::text,NEW.policy_id::text,
  NEW.prompt_artifact_id::text,NEW.prompt_version::text,NEW.prompt_hash,
  NEW.model_config_id::text,NEW.model_config_workflow_id::text,NEW.model_config_version::text,
  NEW.recipient_mode,COALESCE(NEW.recipient_label,''),COALESCE(NEW.recipient_label_evidence_id::text,''),NEW.greeting), 'UTF8')), 'hex');
 IF member IS NULL OR decision IS NULL OR decision.valid_until<=record_org_now()
  OR EXISTS(SELECT 1 FROM record_org_releases r WHERE r.reservation_id=member.reservation_id)
  OR ROW(member.experiment_id,member.candidate_id,member.organization_id,member.recipient_id,member.recipient_source_id,member.reservation_id)
     IS DISTINCT FROM ROW(NEW.experiment_id,NEW.candidate_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id,NEW.reservation_id)
  OR ROW(decision.matrix_id,decision.dossier_id,decision.candidate_id,decision.organization_id,decision.recipient_id,decision.recipient_source_id,decision.offer_acceptance_id,decision.offer_id,decision.profile_id,decision.policy_id)
     IS DISTINCT FROM ROW(NEW.matrix_id,NEW.dossier_id,NEW.candidate_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id,NEW.offer_acceptance_id,NEW.offer_id,NEW.profile_id,NEW.policy_id)
  OR ROW(matrix.dossier_id,matrix.candidate_id,matrix.organization_id,matrix.recipient_id,matrix.recipient_source_id,matrix.offer_acceptance_id,matrix.offer_id,matrix.profile_id,matrix.policy_id)
     IS DISTINCT FROM ROW(NEW.dossier_id,NEW.candidate_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id,NEW.offer_acceptance_id,NEW.offer_id,NEW.profile_id,NEW.policy_id)
  OR ROW(dossier.candidate_id,dossier.organization_id,dossier.recipient_id,dossier.recipient_source_id,dossier.offer_acceptance_id,dossier.offer_id,dossier.profile_id,dossier.policy_id)
     IS DISTINCT FROM ROW(NEW.candidate_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id,NEW.offer_acceptance_id,NEW.offer_id,NEW.profile_id,NEW.policy_id)
  OR ROW(cohort.experiment_id,cohort.offer_acceptance_id,cohort.offer_id,cohort.profile_id,cohort.policy_id)
     IS DISTINCT FROM ROW(NEW.experiment_id,NEW.offer_acceptance_id,NEW.offer_id,NEW.profile_id,NEW.policy_id)
  OR contact.outcome<>'SUPPORTED' OR contact.source_id<>recipient_source.source_fact_id
  OR ROW(contact.source_id,contact.verification_id,contact.resolved_at,contact.valid_until)
     IS DISTINCT FROM ROW(NEW.contact_source_id,NEW.contact_verification_id,NEW.contact_resolved_at,NEW.contact_valid_until)
  OR NOT (contact.resolved_at<=record_org_now() AND record_org_now()<contact.valid_until)
  OR record_org_block_reason(NEW.organization_id,NEW.recipient_id,NEW.experiment_id) IS NOT NULL
  OR cfg.capability<>'OPENAI_GENERATE' OR workflow.experiment_id<>NEW.experiment_id
  OR NOT EXISTS(SELECT 1 FROM record_initial_outreach_policies p WHERE p.id=NEW.policy_id AND p.max_sequence_steps IS NOT NULL)
  OR NOT EXISTS(SELECT 1 FROM record_artifacts a WHERE a.id=NEW.artifact_id AND a.experiment_id=NEW.experiment_id AND a.kind='OUTREACH_CONTEXT_BUNDLE' AND a.version=NEW.artifact_version AND a.content_hash=NEW.artifact_hash AND a.payload->>'recipient_mode'=NEW.recipient_mode AND COALESCE(a.payload->>'recipient_label','')=COALESCE(NEW.recipient_label,'') AND a.payload->>'greeting'=NEW.greeting)
  OR NOT EXISTS(SELECT 1 FROM record_artifacts a WHERE a.id=NEW.prompt_artifact_id AND a.experiment_id=NEW.experiment_id AND a.kind='OUTREACH_PROMPT_CONFIGURATION' AND a.version=NEW.prompt_version AND a.content_hash=NEW.prompt_hash)
 THEN RAISE EXCEPTION 'exact current outreach context required'; END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION record_outreach_used_evidence() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM record_outreach_coverage c WHERE c.context_id=NEW.context_id AND c.evidence_id=NEW.evidence_id AND c.disposition='USED') THEN
  RAISE EXCEPTION 'only used outreach evidence may be referenced';
 END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION record_outreach_complete() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target uuid:=COALESCE(to_jsonb(NEW)->>'context_id',to_jsonb(NEW)->>'id')::uuid; dossier uuid; expected integer; actual integer;
BEGIN
 SELECT dossier_id INTO dossier FROM record_outreach_contexts WHERE id=target;
 IF dossier IS NOT NULL THEN
  SELECT count(*) INTO expected FROM record_qualification_evidence WHERE dossier_id=dossier;
  SELECT count(*) INTO actual FROM record_outreach_coverage WHERE context_id=target;
  IF actual<>expected THEN RAISE EXCEPTION 'complete outreach evidence coverage required'; END IF;
  IF EXISTS(SELECT 1 FROM record_outreach_contexts c WHERE c.id=target AND c.recipient_mode<>'GENERAL_BUSINESS_INBOX' AND NOT EXISTS(SELECT 1 FROM record_outreach_coverage x WHERE x.context_id=c.id AND x.evidence_id=c.recipient_label_evidence_id AND x.disposition='USED')) THEN RAISE EXCEPTION 'recipient label requires used evidence'; END IF;
 END IF;
 RETURN NULL;
END $$;

CREATE FUNCTION record_outreach_claim_complete() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE claim record_outreach_claims;
BEGIN
 SELECT * INTO claim FROM record_outreach_claims WHERE artifact_id=NEW.artifact_id AND ordinal=NEW.ordinal;
 IF claim.kind='FACTUAL' AND NOT EXISTS(SELECT 1 FROM record_outreach_claim_evidence e WHERE e.artifact_id=claim.artifact_id AND e.ordinal=claim.ordinal) THEN RAISE EXCEPTION 'factual claim evidence required'; END IF;
 IF claim.kind='COMMERCIAL' AND NOT EXISTS(SELECT 1 FROM record_outreach_claim_offer_fields f WHERE f.artifact_id=claim.artifact_id AND f.ordinal=claim.ordinal) THEN RAISE EXCEPTION 'commercial claim offer field required'; END IF;
 RETURN NULL;
END $$;

CREATE FUNCTION record_outreach_offer_field_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM record_outreach_contexts c WHERE c.id=NEW.context_id AND c.offer_id=NEW.offer_id) THEN
  RAISE EXCEPTION 'commercial claim requires exact context offer field';
 END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION record_outreach_draft_guard() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
 IF NOT EXISTS(SELECT 1 FROM record_outreach_contexts c JOIN record_artifacts a ON a.id=NEW.artifact_id WHERE c.id=NEW.context_id AND a.kind='EMAIL_DRAFT' AND a.payload->>'recipient_mode'=c.recipient_mode AND a.payload->>'greeting'=c.greeting)
  OR NOT EXISTS(SELECT 1 FROM record_outreach_documents d WHERE d.artifact_id=NEW.narrative_artifact_id AND d.context_id=NEW.context_id AND d.kind='LEAD_OPPORTUNITY_NARRATIVE')
  OR NOT EXISTS(SELECT 1 FROM record_outreach_documents d WHERE d.artifact_id=NEW.strategy_artifact_id AND d.context_id=NEW.context_id AND d.kind='CONVERSATION_STRATEGY')
  OR NOT EXISTS(SELECT 1 FROM record_outreach_documents d WHERE d.artifact_id=NEW.sequence_artifact_id AND d.context_id=NEW.context_id AND d.kind='OUTREACH_SEQUENCE_PLAN')
  OR NOT EXISTS(SELECT 1 FROM record_outreach_subjects s JOIN record_artifacts a ON a.id=NEW.artifact_id WHERE s.id=NEW.subject_id AND s.context_id=NEW.context_id AND a.payload->>'subject'=s.text)
 THEN RAISE EXCEPTION 'draft recipient, greeting, subject and artifact lineage must match context'; END IF;
 RETURN NEW;
END $$;

CREATE FUNCTION record_outreach_validation_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE d record_outreach_drafts; context record_outreach_contexts; policy record_initial_outreach_policies; steps integer; max_ordinal integer; plan_count integer;
BEGIN
 SELECT * INTO d FROM record_outreach_drafts WHERE artifact_id=NEW.draft_artifact_id;
 SELECT * INTO context FROM record_outreach_contexts WHERE id=d.context_id;
 SELECT * INTO policy FROM record_initial_outreach_policies WHERE id=context.policy_id;
 SELECT count(*),max(ordinal) INTO steps,max_ordinal FROM record_outreach_sequence_steps WHERE sequence_artifact_id=d.sequence_artifact_id;
 SELECT (payload->>'step_count')::integer INTO plan_count FROM record_artifacts WHERE id=d.sequence_artifact_id;
 IF d IS NULL OR d.recipient_mode<>context.recipient_mode OR d.greeting<>context.greeting
  OR NOT EXISTS(SELECT 1 FROM record_outreach_documents x WHERE x.artifact_id=d.narrative_artifact_id AND x.kind='LEAD_OPPORTUNITY_NARRATIVE')
  OR NOT EXISTS(SELECT 1 FROM record_outreach_documents x WHERE x.artifact_id=d.strategy_artifact_id AND x.kind='CONVERSATION_STRATEGY')
  OR NOT EXISTS(SELECT 1 FROM record_outreach_documents x WHERE x.artifact_id=d.sequence_artifact_id AND x.kind='OUTREACH_SEQUENCE_PLAN')
  OR NOT EXISTS(SELECT 1 FROM record_outreach_documents x WHERE x.artifact_id=d.artifact_id AND x.kind='EMAIL_DRAFT')
  OR NOT EXISTS(SELECT 1 FROM record_outreach_subjects s JOIN record_artifacts a ON a.id=d.artifact_id WHERE s.id=d.subject_id AND s.context_id=d.context_id AND a.payload->>'subject'=s.text AND a.payload->>'recipient_mode'=d.recipient_mode AND a.payload->>'greeting'=d.greeting)
  OR EXISTS(SELECT 1 FROM record_outreach_claim_offer_fields f WHERE f.context_id=d.context_id AND f.offer_id<>context.offer_id)
  OR (SELECT count(*) FROM record_outreach_draft_angles a WHERE a.draft_artifact_id=d.artifact_id AND a.role='PRIMARY')<>1
  OR (SELECT count(*) FROM record_outreach_draft_angles a WHERE a.draft_artifact_id=d.artifact_id AND a.role='SUPPORTING')>1
  OR (SELECT count(*) FROM record_outreach_draft_ctas c WHERE c.draft_artifact_id=d.artifact_id)>1
  OR policy.max_sequence_steps IS NULL OR steps=0 OR max_ordinal<>steps OR steps<>plan_count OR steps>policy.max_sequence_steps
  OR NEW.disposition<>'PASS' OR cardinality(NEW.reason_codes)<>0
  OR NOT EXISTS(SELECT 1 FROM record_artifacts a WHERE a.id=NEW.artifact_id AND a.kind='DRAFT_VALIDATION_RESULT' AND a.payload->>'validator'=NEW.validator AND a.payload->>'input_hash'=NEW.input_hash AND a.payload->>'disposition'=NEW.disposition AND a.payload->'reason_codes'=to_jsonb(NEW.reason_codes))
 THEN RAISE EXCEPTION 'accepted outreach draft failed deterministic validation'; END IF;
 RETURN NULL;
END $$;
""")
    for name in (
        "contexts",
        "coverage",
        "angles",
        "angle_evidence",
        "documents",
        "claims",
        "claim_evidence",
        "claim_offer_fields",
        "subjects",
        "subject_evidence",
        "sequence_steps",
        "drafts",
        "draft_angles",
        "draft_ctas",
        "validations",
    ):
        op.execute(
            f"CREATE TRIGGER record_outreach_{name}_immutable BEFORE UPDATE OR DELETE ON record_outreach_{name} FOR EACH ROW EXECUTE FUNCTION record_outreach_immutable()"
        )
    op.execute(
        "CREATE TRIGGER record_outreach_context_guard BEFORE INSERT ON record_outreach_contexts FOR EACH ROW EXECUTE FUNCTION record_outreach_context_guard()"
    )
    op.execute(
        "CREATE TRIGGER record_outreach_claim_offer_guard BEFORE INSERT ON record_outreach_claim_offer_fields FOR EACH ROW EXECUTE FUNCTION record_outreach_offer_field_guard()"
    )
    op.execute(
        "CREATE TRIGGER record_outreach_draft_guard BEFORE INSERT ON record_outreach_drafts FOR EACH ROW EXECUTE FUNCTION record_outreach_draft_guard()"
    )
    for name in ("angle_evidence", "claim_evidence", "subject_evidence"):
        op.execute(
            f"CREATE TRIGGER record_outreach_{name}_used BEFORE INSERT ON record_outreach_{name} FOR EACH ROW EXECUTE FUNCTION record_outreach_used_evidence()"
        )
    op.execute(
        "CREATE CONSTRAINT TRIGGER record_outreach_context_complete AFTER INSERT ON record_outreach_contexts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION record_outreach_complete()"
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER record_outreach_coverage_complete AFTER INSERT ON record_outreach_coverage DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION record_outreach_complete()"
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER record_outreach_claim_complete AFTER INSERT ON record_outreach_claims DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION record_outreach_claim_complete()"
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER record_outreach_validation_complete AFTER INSERT ON record_outreach_validations DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION record_outreach_validation_guard()"
    )


def downgrade() -> None:
    op.execute(r"""
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM record_artifacts WHERE kind IN (
   'OUTREACH_PROMPT_CONFIGURATION','OUTREACH_CONTEXT_BUNDLE','LEAD_OPPORTUNITY_NARRATIVE',
   'CONVERSATION_STRATEGY','OUTREACH_SEQUENCE_PLAN','EMAIL_DRAFT','DRAFT_VALIDATION_RESULT'))
  OR EXISTS(SELECT 1 FROM record_initial_outreach_policies WHERE max_sequence_steps IS NOT NULL)
 THEN RAISE EXCEPTION 'outreach policy and draft history cannot be represented by previous schema'; END IF;
END $$;
""")
    op.execute(
        "DROP TRIGGER record_outreach_validation_complete ON record_outreach_validations"
    )
    op.execute("DROP TRIGGER record_outreach_claim_complete ON record_outreach_claims")
    op.execute(
        "DROP TRIGGER record_outreach_coverage_complete ON record_outreach_coverage"
    )
    op.execute(
        "DROP TRIGGER record_outreach_context_complete ON record_outreach_contexts"
    )
    for name in ("angle_evidence", "claim_evidence", "subject_evidence"):
        op.execute(
            f"DROP TRIGGER record_outreach_{name}_used ON record_outreach_{name}"
        )
    op.execute("DROP TRIGGER record_outreach_context_guard ON record_outreach_contexts")
    op.execute(
        "DROP TRIGGER IF EXISTS record_outreach_claim_offer_guard ON record_outreach_claim_offer_fields"
    )
    op.execute(
        "DROP TRIGGER IF EXISTS record_outreach_draft_guard ON record_outreach_drafts"
    )
    for name in (
        "contexts",
        "coverage",
        "angles",
        "angle_evidence",
        "documents",
        "claims",
        "claim_evidence",
        "claim_offer_fields",
        "subjects",
        "subject_evidence",
        "sequence_steps",
        "drafts",
        "draft_angles",
        "draft_ctas",
        "validations",
    ):
        op.execute(
            f"DROP TRIGGER record_outreach_{name}_immutable ON record_outreach_{name}"
        )
    op.execute("DROP FUNCTION record_outreach_validation_guard()")
    op.execute("DROP FUNCTION record_outreach_claim_complete()")
    op.execute("DROP FUNCTION IF EXISTS record_outreach_draft_guard()")
    op.execute("DROP FUNCTION IF EXISTS record_outreach_offer_field_guard()")
    op.execute("DROP FUNCTION record_outreach_complete()")
    op.execute("DROP FUNCTION record_outreach_used_evidence()")
    op.execute("DROP FUNCTION record_outreach_context_guard()")
    op.execute("DROP FUNCTION record_outreach_immutable()")
    op.execute("DROP FUNCTION record_payload_valid(text,jsonb)")
    op.execute(
        "ALTER FUNCTION record_payload_valid_pre_outreach(text,jsonb) RENAME TO record_payload_valid"
    )
    for name in (
        "validations",
        "draft_ctas",
        "draft_angles",
        "subject_evidence",
        "drafts",
        "claim_offer_fields",
        "claim_evidence",
        "subjects",
        "sequence_steps",
        "claims",
        "angle_evidence",
        "documents",
        "coverage",
        "angles",
        "contexts",
    ):
        op.drop_table("record_outreach_" + name)
    op.execute(
        "ALTER TABLE record_artifacts DROP CONSTRAINT record_artifacts_kind_check"
    )
    op.execute("""
ALTER TABLE record_artifacts ADD CONSTRAINT record_artifacts_kind_check CHECK(kind IN (
 'EXPERIMENT_BRIEF','IDEA_SEED','IDEA_CANDIDATE','IDEA_BRIEF','RESEARCH_PLAN','RESEARCH_EVIDENCE',
 'COMPETITOR_PROFILE','SERVICE_PROFILE','PRICE_OBSERVATION','MARKET_RESEARCH_REPORT',
 'MARKET_RESEARCH_RECOMMENDATION','RESEARCH_FEEDBACK_BRIEF','OFFER_RESEARCH_GAP_BRIEF',
 'DELIVERY_SCOPE_ESTIMATE','OFFER_DESIGN_INPUT_BUNDLE','COMMERCIAL_DESIGN_ENVELOPE',
 'OFFER_DESIGN_PROPOSAL','OFFER_PACKAGE','OFFER_QUALIFICATION_PROFILE','INITIAL_OUTREACH_POLICY',
 'VALIDATION_RESULT','ACCEPTANCE_RECEIPT'))
""")
    op.drop_constraint(
        "record_initial_outreach_policies_sequence_check",
        "record_initial_outreach_policies",
        type_="check",
    )
    op.drop_column("record_initial_outreach_policies", "max_sequence_steps")
