"""qualification cohorts

Revision ID: 20260920_09
Revises: 20260913_08
Create Date: 2026-09-20 11:23:12.479037

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20260920_09"
down_revision: str | Sequence[str] | None = "20260913_08"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "record_qualification_cohorts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("offer_acceptance_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("target_size", sa.Integer(), nullable=False),
        sa.Column("frozen_by", sa.UUID(), nullable=False),
        sa.Column("frozen_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("target_size=50"),
        sa.ForeignKeyConstraint(
            ["offer_acceptance_id", "experiment_id"],
            ["record_offer_acceptances.id", "record_offer_acceptances.experiment_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("experiment_id"),
        sa.UniqueConstraint("id", "experiment_id"),
    )
    op.create_table(
        "record_qualification_dossiers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("binding_id", sa.UUID(), nullable=False),
        sa.Column("admission_id", sa.UUID(), nullable=False),
        sa.Column("recipient_source_id", sa.UUID(), nullable=False),
        sa.Column("offer_acceptance_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("version>0"),
        sa.ForeignKeyConstraint(
            ["admission_id"],
            ["record_org_admissions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["binding_id", "experiment_id", "organization_id"],
            [
                "record_org_bindings.id",
                "record_org_bindings.experiment_id",
                "record_org_bindings.organization_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_id", "experiment_id"],
            ["supply_candidates.id", "supply_candidates.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["offer_acceptance_id", "experiment_id"],
            ["record_offer_acceptances.id", "record_offer_acceptances.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["offer_id", "experiment_id"],
            ["record_offer_packages.id", "record_offer_packages.experiment_id"],
        ),
        sa.ForeignKeyConstraint(
            ["policy_id"],
            ["record_initial_outreach_policies.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["record_offer_qualification_profiles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["recipient_source_id", "experiment_id", "organization_id", "recipient_id"],
            [
                "record_org_recipient_sources.id",
                "record_org_recipient_sources.experiment_id",
                "record_org_recipient_sources.organization_id",
                "record_org_recipient_sources.recipient_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("candidate_id", "version"),
        sa.UniqueConstraint("id", "experiment_id"),
    )
    op.create_table(
        "record_qualification_evidence",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("code", sa.String(length=64), nullable=False),
        sa.Column("kind", sa.String(length=24), nullable=False),
        sa.Column("source_ref", sa.String(length=1000), nullable=False),
        sa.Column("excerpt", sa.String(length=4000), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=False),
        sa.CheckConstraint(
            "kind IN ('OBSERVED_FACT','HYPOTHESIS','CONTRADICTION','UNKNOWN')"
        ),
        sa.CheckConstraint("observed_at<valid_until AND confidence BETWEEN 0 AND 1"),
        sa.ForeignKeyConstraint(
            ["dossier_id", "experiment_id"],
            [
                "record_qualification_dossiers.id",
                "record_qualification_dossiers.experiment_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dossier_id", "code"),
        sa.UniqueConstraint("id", "dossier_id"),
    )
    op.create_table(
        "record_qualification_matrices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("recipient_source_id", sa.UUID(), nullable=False),
        sa.Column("offer_acceptance_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["dossier_id", "experiment_id"],
            [
                "record_qualification_dossiers.id",
                "record_qualification_dossiers.experiment_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dossier_id"),
        sa.UniqueConstraint("id", "dossier_id"),
        sa.UniqueConstraint("id", "profile_id"),
    )
    op.create_table(
        "record_qualification_criterion_results",
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("criterion_code", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("rationale", sa.String(length=2000), nullable=False),
        sa.CheckConstraint(
            "status IN ('SATISFIED','PARTIAL','NOT_SATISFIED','UNKNOWN','CONTRADICTED')"
        ),
        sa.ForeignKeyConstraint(
            ["matrix_id", "profile_id"],
            [
                "record_qualification_matrices.id",
                "record_qualification_matrices.profile_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id", "criterion_code"],
            [
                "record_qualification_criteria.profile_id",
                "record_qualification_criteria.code",
            ],
        ),
        sa.PrimaryKeyConstraint("matrix_id", "criterion_code"),
    )
    op.create_unique_constraint(
        "uq_supply_qualification_exact",
        "supply_qualifications",
        ["candidate_id", "experiment_id", "fact_id"],
    )
    op.create_table(
        "record_qualification_decisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("recipient_source_id", sa.UUID(), nullable=False),
        sa.Column("offer_acceptance_id", sa.UUID(), nullable=False),
        sa.Column("offer_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("policy_id", sa.UUID(), nullable=False),
        sa.Column("proposal_fact_id", sa.UUID(), nullable=False),
        sa.Column("outcome", sa.String(length=48), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("finding_codes", sa.ARRAY(sa.String(length=64)), nullable=False),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_by", sa.UUID(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "outcome IN ('QUALIFIED_CONTACTABLE','PILOT_FIT_CONTACTABLE','REJECTED_NOT_A_FIT','REJECTED_NO_RELEVANT_PROBLEM_SIGNAL','REJECTED_ALREADY_ADEQUATELY_SOLVED','REJECTED_TECHNICAL_MISMATCH','REJECTED_ECONOMIC_MISMATCH','REJECTED_BUYER_MISMATCH','REJECTED_INSUFFICIENT_EVIDENCE','BLOCKED_POLICY_OR_IDENTITY','REVIEW_REQUIRED')"
        ),
        sa.CheckConstraint("cardinality(finding_codes)>0 AND decided_at<valid_until"),
        sa.ForeignKeyConstraint(
            ["candidate_id", "experiment_id", "proposal_fact_id"],
            [
                "supply_qualifications.candidate_id",
                "supply_qualifications.experiment_id",
                "supply_qualifications.fact_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["matrix_id", "dossier_id"],
            [
                "record_qualification_matrices.id",
                "record_qualification_matrices.dossier_id",
            ],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("dossier_id"),
        sa.UniqueConstraint("id", "experiment_id"),
        sa.UniqueConstraint("id", "offer_acceptance_id"),
        sa.UniqueConstraint("matrix_id"),
        sa.UniqueConstraint("proposal_fact_id"),
    )
    op.create_table(
        "record_qualification_cohort_members",
        sa.Column("cohort_id", sa.UUID(), nullable=False),
        sa.Column("experiment_id", sa.UUID(), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("decision_id", sa.UUID(), nullable=False),
        sa.Column("candidate_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("recipient_id", sa.UUID(), nullable=False),
        sa.Column("recipient_source_id", sa.UUID(), nullable=False),
        sa.Column("reservation_id", sa.UUID(), nullable=False),
        sa.CheckConstraint("ordinal BETWEEN 1 AND 50"),
        sa.ForeignKeyConstraint(
            ["cohort_id", "experiment_id"],
            [
                "record_qualification_cohorts.id",
                "record_qualification_cohorts.experiment_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["decision_id", "experiment_id"],
            [
                "record_qualification_decisions.id",
                "record_qualification_decisions.experiment_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["reservation_id"],
            ["record_org_reservations.id"],
        ),
        sa.PrimaryKeyConstraint("cohort_id", "ordinal"),
        sa.UniqueConstraint("cohort_id", "candidate_id"),
        sa.UniqueConstraint("cohort_id", "decision_id"),
        sa.UniqueConstraint("cohort_id", "organization_id"),
        sa.UniqueConstraint("cohort_id", "recipient_id"),
        sa.UniqueConstraint("cohort_id", "recipient_source_id"),
        sa.UniqueConstraint("reservation_id"),
    )
    op.create_table(
        "record_qualification_result_evidence",
        sa.Column("matrix_id", sa.UUID(), nullable=False),
        sa.Column("criterion_code", sa.String(length=32), nullable=False),
        sa.Column("dossier_id", sa.UUID(), nullable=False),
        sa.Column("evidence_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evidence_id", "dossier_id"],
            [
                "record_qualification_evidence.id",
                "record_qualification_evidence.dossier_id",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["matrix_id", "criterion_code"],
            [
                "record_qualification_criterion_results.matrix_id",
                "record_qualification_criterion_results.criterion_code",
            ],
        ),
        sa.ForeignKeyConstraint(
            ["matrix_id", "dossier_id"],
            [
                "record_qualification_matrices.id",
                "record_qualification_matrices.dossier_id",
            ],
        ),
        sa.PrimaryKeyConstraint("matrix_id", "criterion_code", "evidence_id"),
    )
    op.execute("""
CREATE FUNCTION record_qualification_guard() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE d record_qualification_dossiers; m record_qualification_matrices; decision record_qualification_decisions; cohort record_qualification_cohorts; acceptance record_offer_acceptances; result_count integer; criterion_count integer;
BEGIN
 IF TG_OP<>'INSERT' THEN RAISE EXCEPTION 'immutable qualification record'; END IF;
 IF TG_TABLE_NAME='record_qualification_dossiers' THEN
  SELECT * INTO acceptance FROM record_offer_acceptances WHERE id=NEW.offer_acceptance_id;
  IF ROW(acceptance.experiment_id,acceptance.offer_id,acceptance.profile_id,acceptance.policy_id) IS DISTINCT FROM ROW(NEW.experiment_id,NEW.offer_id,NEW.profile_id,NEW.policy_id)
   OR NOT EXISTS(SELECT 1 FROM supply_candidates c JOIN record_org_bindings b ON b.identity_id=c.identity_id AND b.id=NEW.binding_id JOIN record_org_admissions a ON a.binding_id=b.id AND a.id=NEW.admission_id JOIN record_org_recipient_sources r ON r.binding_id=b.id AND r.candidate_id=c.id AND r.id=NEW.recipient_source_id WHERE c.id=NEW.candidate_id AND c.experiment_id=NEW.experiment_id AND b.organization_id=NEW.organization_id AND r.recipient_id=NEW.recipient_id)
  THEN RAISE EXCEPTION 'exact dossier lineage required'; END IF;
 ELSIF TG_TABLE_NAME='record_qualification_matrices' THEN
  SELECT * INTO d FROM record_qualification_dossiers WHERE id=NEW.dossier_id;
  IF ROW(d.experiment_id,d.candidate_id,d.organization_id,d.recipient_id,d.recipient_source_id,d.offer_acceptance_id,d.offer_id,d.profile_id,d.policy_id) IS DISTINCT FROM ROW(NEW.experiment_id,NEW.candidate_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id,NEW.offer_acceptance_id,NEW.offer_id,NEW.profile_id,NEW.policy_id) THEN RAISE EXCEPTION 'exact matrix lineage required'; END IF;
 ELSIF TG_TABLE_NAME='record_qualification_decisions' THEN
  SELECT * INTO m FROM record_qualification_matrices WHERE id=NEW.matrix_id;
  SELECT count(*) INTO result_count FROM record_qualification_criterion_results r WHERE r.matrix_id=NEW.matrix_id AND EXISTS(SELECT 1 FROM record_qualification_result_evidence e WHERE e.matrix_id=r.matrix_id AND e.criterion_code=r.criterion_code);
  SELECT count(*) INTO criterion_count FROM record_qualification_criteria WHERE profile_id=NEW.profile_id;
  IF ROW(m.experiment_id,m.dossier_id,m.candidate_id,m.organization_id,m.recipient_id,m.recipient_source_id,m.offer_acceptance_id,m.offer_id,m.profile_id,m.policy_id) IS DISTINCT FROM ROW(NEW.experiment_id,NEW.dossier_id,NEW.candidate_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id,NEW.offer_acceptance_id,NEW.offer_id,NEW.profile_id,NEW.policy_id)
   OR result_count<>criterion_count
   OR NEW.offer_acceptance_id IS DISTINCT FROM (SELECT id FROM record_offer_acceptances WHERE experiment_id=NEW.experiment_id ORDER BY accepted_at DESC,id DESC LIMIT 1)
   OR (NEW.outcome IN ('QUALIFIED_CONTACTABLE','PILOT_FIT_CONTACTABLE') AND EXISTS(SELECT 1 FROM record_qualification_criterion_results r JOIN record_qualification_criteria c ON c.profile_id=r.profile_id AND c.code=r.criterion_code WHERE r.matrix_id=NEW.matrix_id AND ((c.rule_kind='HARD_GATE' AND r.status<>'SATISFIED') OR (c.rule_kind='FATAL_DISQUALIFIER' AND r.status<>'NOT_SATISFIED'))))
   OR (NEW.outcome='PILOT_FIT_CONTACTABLE' AND NOT EXISTS(SELECT 1 FROM record_qualification_criterion_results r JOIN record_qualification_criteria c ON c.profile_id=r.profile_id AND c.code=r.criterion_code WHERE r.matrix_id=NEW.matrix_id AND c.category='PILOT_FIT' AND r.status='SATISFIED'))
   OR NOT EXISTS(SELECT 1 FROM supply_qualifications sq WHERE sq.candidate_id=NEW.candidate_id AND sq.experiment_id=NEW.experiment_id AND sq.fact_id=NEW.proposal_fact_id AND ((NEW.outcome IN ('QUALIFIED_CONTACTABLE','PILOT_FIT_CONTACTABLE') AND sq.outcome='QUALIFIED') OR (NEW.outcome NOT IN ('QUALIFIED_CONTACTABLE','PILOT_FIT_CONTACTABLE') AND sq.outcome<>'QUALIFIED')))
  THEN RAISE EXCEPTION 'complete authoritative qualification required'; END IF;
 ELSIF TG_TABLE_NAME='record_qualification_cohorts' THEN
  SELECT * INTO acceptance FROM record_offer_acceptances WHERE id=NEW.offer_acceptance_id;
  IF ROW(acceptance.experiment_id,acceptance.offer_id,acceptance.profile_id,acceptance.policy_id) IS DISTINCT FROM ROW(NEW.experiment_id,NEW.offer_id,NEW.profile_id,NEW.policy_id)
   OR NEW.offer_acceptance_id IS DISTINCT FROM (SELECT id FROM record_offer_acceptances WHERE experiment_id=NEW.experiment_id ORDER BY accepted_at DESC,id DESC LIMIT 1)
  THEN RAISE EXCEPTION 'exact cohort offer required'; END IF;
 ELSIF TG_TABLE_NAME='record_qualification_cohort_members' THEN
  SELECT * INTO decision FROM record_qualification_decisions WHERE id=NEW.decision_id;
  SELECT * INTO cohort FROM record_qualification_cohorts WHERE id=NEW.cohort_id;
  IF decision.outcome NOT IN ('QUALIFIED_CONTACTABLE','PILOT_FIT_CONTACTABLE') OR decision.valid_until<=record_org_now()
   OR ROW(decision.experiment_id,decision.candidate_id,decision.organization_id,decision.recipient_id,decision.recipient_source_id) IS DISTINCT FROM ROW(NEW.experiment_id,NEW.candidate_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id)
   OR ROW(decision.experiment_id,decision.offer_acceptance_id,decision.offer_id,decision.profile_id,decision.policy_id) IS DISTINCT FROM ROW(cohort.experiment_id,cohort.offer_acceptance_id,cohort.offer_id,cohort.profile_id,cohort.policy_id)
   OR NOT EXISTS(SELECT 1 FROM record_org_reservations r WHERE r.id=NEW.reservation_id AND ROW(r.experiment_id,r.organization_id,r.recipient_id,r.source_id)=ROW(NEW.experiment_id,NEW.organization_id,NEW.recipient_id,NEW.recipient_source_id))
  THEN RAISE EXCEPTION 'invalid cohort member'; END IF;
 END IF;
 RETURN NEW;
END $$;
CREATE FUNCTION record_qualification_exact_cohort() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE target uuid:=COALESCE(to_jsonb(NEW)->>'cohort_id',to_jsonb(NEW)->>'id')::uuid;
BEGIN
 IF (SELECT count(*) FROM record_qualification_cohort_members WHERE cohort_id=target)<>50 THEN RAISE EXCEPTION 'cohort must contain exactly 50 members'; END IF;
 RETURN NULL;
END $$;
""")
    for name in (
        "dossiers",
        "evidence",
        "matrices",
        "criterion_results",
        "result_evidence",
        "decisions",
        "cohorts",
        "cohort_members",
    ):
        op.execute(
            f"CREATE TRIGGER record_qualification_{name}_guard BEFORE INSERT OR UPDATE OR DELETE ON record_qualification_{name} FOR EACH ROW EXECUTE FUNCTION record_qualification_guard()"
        )
    op.execute(
        "CREATE CONSTRAINT TRIGGER record_qualification_cohort_exact AFTER INSERT ON record_qualification_cohorts DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION record_qualification_exact_cohort()"
    )
    op.execute(
        "CREATE CONSTRAINT TRIGGER record_qualification_member_exact AFTER INSERT ON record_qualification_cohort_members DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION record_qualification_exact_cohort()"
    )


def downgrade() -> None:
    op.execute(
        "DROP TRIGGER record_qualification_member_exact ON record_qualification_cohort_members"
    )
    op.execute(
        "DROP TRIGGER record_qualification_cohort_exact ON record_qualification_cohorts"
    )
    for name in reversed(
        (
            "dossiers",
            "evidence",
            "matrices",
            "criterion_results",
            "result_evidence",
            "decisions",
            "cohorts",
            "cohort_members",
        )
    ):
        op.execute(
            f"DROP TRIGGER record_qualification_{name}_guard ON record_qualification_{name}"
        )
    op.execute("DROP FUNCTION record_qualification_exact_cohort()")
    op.execute("DROP FUNCTION record_qualification_guard()")
    op.drop_table("record_qualification_result_evidence")
    op.drop_table("record_qualification_cohort_members")
    op.drop_table("record_qualification_decisions")
    op.drop_table("record_qualification_criterion_results")
    op.drop_table("record_qualification_matrices")
    op.drop_table("record_qualification_evidence")
    op.drop_table("record_qualification_dossiers")
    op.drop_table("record_qualification_cohorts")
    op.drop_constraint(
        "uq_supply_qualification_exact", "supply_qualifications", type_="unique"
    )
